include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    # strict-casts: true
    # strict-inference: true
    # strict-raw-types: true

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

  errors:
    invalid_annotation_target: ignore

# linter:
#   rules:
#     - prefer_collection_literals
#     - prefer_conditional_assignment
#     - prefer_const_constructors
#     - prefer_const_constructors_in_immutables
#     - prefer_const_declarations
#     - prefer_const_literals_to_create_immutables
#     - avoid_unnecessary_containers
#     - sized_box_for_whitespace
#     - sized_box_shrink_expand
#     - use_colored_box
#     - avoid_empty_else
#     - avoid_print
#     - avoid_function_literals_in_foreach_calls